<?php
$fname = $_SERVER['argv'][1];
$comment_block = false;
$title = "$fname - Zig standard library";
?>
<html>
<head>
    <title><?=$title?></title>
    <style>
        body { color: #777; background-color: #F2F2F2; }
        code { display: block; white-space: pre; }
        a { font-weight: bold; }
        .comment {
            color: #222;
            padding: .8em 0;
            background-color: #FFF;
            white-space: pre;
        }
        .pub-fn { color: #700; font-weight: bold; }
        .pub-const { color: #070; font-weight: bold; }
    </style>
</head>
<body>
<h1><?=$title?></h1>

<?php foreach(file($fname) as $line){
    $line = rtrim($line);

    // Look for whole-line comments and start a comment block.
    if (preg_match("/^\s*\/{2}/", $line)) {
        if(!$comment_block){
            $comment_block = true;
            echo "<div class=\"comment\">";
        }
        echo "$line<br>";
        continue;
    }

    // Not a comment, end block if it was still open.
    if($comment_block){
        echo "</div>";
        $comment_block = false;
    }

    // Make links from imports
    $line = preg_replace("/@import\(\"(.*zig)\"\)/", "@import(\"<a href=\"$1.html\">$1</a>\")", $line);

    // Highlight pub fns
    $line = preg_replace("/pub fn (\w+)/", "pub fn <span class=\"pub-fn\">$1</span>", $line);

    // Highlight pub const X
    $line = preg_replace("/pub const (\w+)/", "pub const <span class=\"pub-const\">$1</span>", $line);

    echo "<code>$line</code>";
}
?>

Generated by <a href="">stdlib-browseable</a> on <?=date()?>.
</body>
</html>
